### ISSUE TITLE
Error calling `eldoc-box-eglot-help-at-point`

### ISSUE THREAD

**Issue by andreyorst** [casouri/eldoc-box#25] opened 2019-12-18 11:46 UTC
When I try to call `eldoc-box-eglot-help-at-point` manually I get this error message:

     Symbol’s value as variable is void: contents

**Comment by casouri** [comment] 2019-12-18 22:28
Weird, can you confirm that this happens on vanilla Emacs? What's the version of eglot and Emacs?

I tried this function on the latest melpa eglot and it seems to work ok.

**Comment by andreyorst** [comment] 2019-12-19 14:08
eglot from melpa: 20191218.1244
emacs build from master: 5aab1e83f55ccbf7affc25272f6b1107aa17598c

**Comment by lxsameer** [comment] 2021-04-18 00:58
I suffer from the same issue. I'm on emacs compiled from source from the main branch. (pulled the changes of today) and I just installed eldoc-box from melpa

**Comment by casouri** [comment] 2021-04-18 19:53
Weird, I just tried it again and it worked fine. Could you try enabling debug on error like this:
```
M-x toggle-debug-on-error RET
```
call the command and post the backtrace here?

**Comment by syvanpera** [comment] 2021-06-18 04:47
I just found this package and wanted to try it out with eglot, but I'm getting the same error when using that function

**Comment by casouri** [comment] 2021-06-22 20:51
I just tried again with the latest eglot and couldn't reproduce it. Are you sure that eglot is loaded when you call `eldoc-box-eglot-help-at-point`?

**Comment by Jemoka** [comment] 2021-08-19 06:10
this issue was solved for me because I accidentally had `(setq eglot-stay-out-of '(eldoc))`, which, of course, rendered it rather useless... 😅

**Comment by zikajk** [comment] 2022-03-27 06:29
This is the backtrace - I am getting this error with vanilla@29
```
Debugger entered--Lisp error: (void-variable contents)
  eldoc-box-eglot-help-at-point()
  funcall-interactively(eldoc-box-eglot-help-at-point)
  call-interactively(eldoc-box-eglot-help-at-point record nil)
  command-execute(eldoc-box-eglot-help-at-point record)
  execute-extended-command(nil "eldoc-box-eglot-help-at-point" nil)
  funcall-interactively(execute-extended-command nil "eldoc-box-eglot-help-at-point" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

```

**Comment by anticomputer** [comment] 2022-03-30 03:58
Ran into the same issue, took a quick swing at fixing it in https://github.com/casouri/eldoc-box/pull/41

**Comment by anticomputer** [comment] 2022-03-30 05:11
I ran into this as well on emacs 28+, it was due to byte compilation not having the eglot defmacros available, I proposed a fix for this and an adjacent issue in: https://github.com/casouri/eldoc-box/pull/42

**Comment by casouri** [comment] 2022-06-12 03:04
Seems that this is fixed, so imma close it. Reopen if the issue still exists, of course.

**Closed by casouri** 2022-06-12 03:04 UTC
